export const SET_INITIAL_STATE = 'SET_INITIAL_STATE';
export const SET_USER_POSITION = 'SET_USER_POSITION';
export const SET_ERROR = 'SET_ERROR';
export const SET_CURRENT_CLASSES = 'SET_CURRENT_CLASSES';
export const TOGGLE_SORT = 'TOGGLE_SORT';
